---
- name: "Apache installation"
  hosts: all
  tasks:
    - name: "Install apache package"
      yum:
        name: "httpd"
        state: "present"
    - name: "Start apache service"
      service:
        name: "httpd"
        state: "started"
        enabled: yes
    - name: "Copy test.html"
      copy:
        src: "test.html"
        dest: "/var/www/html"
        owner: "apache"
        group: "apache"
    - name: "autoriser le service http"
      firewalld:
        immediate: true
        service: http
        permanent: true
        state: enabled
    - name: "autoriser le service https"
      firewalld:
        immediate: true
        service: https
        permanent: true
        state: enabled
        
[active-directory]
active-directory-1 ansible_connection=winrm
[container]
container-1 ansible_connection=docker
          
        
