- name: "generate html file for each host"
  hosts: all
  gather_facts: yes
  tasks:
    - name: "html file generation"
      template:
        src: "network_interfaces.html.j2"
        dest: "{{playbook_dir}}/{{inventory_hostname}}.html"
      connection: local
      
